
# Get all data
GET http://localhost:4000/api/kost
Content-Type: application/json

###

# Get single data by id
GET http://localhost:4000/api/kost/3
Content-Type: application/json

###

# Create new data
POST http://localhost:4000/api/kost
Content-Type: application/json

{
    "nama": "Kamar 2",
    "deskripsi": "Cihuy 2",
    "harga": 200000
}

###

# Update data
PUT http://localhost:4000/api/kost/1
Content-Type: application/json

{
    "nama": "Kamar 2",
    "deskripsi": "Cihuy 2",
    "harga": 400000
}

###

# Delete data
DELETE http://localhost:4000/api/kost/3
Content-Type: application/json
